version: 2
jobs:
  build:
    working_directory: /app
    environment:
      PROJECT_NAME: boxp-tk
      CLUSTER_NAME: alice
      CLOUDSDK_COMPUTE_ZONE: asia-northeast1-a
      DEBIAN_FRONTEND: noninteractive
      GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/account-auth.json
    docker:
      - image: google/cloud-sdk:343.0.0-alpine
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-
          paths:
            - /caches/app.tar
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              gettext
            pip install \
              docker-compose==1.12.0
            gcloud components install kubectl
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Check docker version
          command: |
            docker version
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=asia.gcr.io/${PROJECT_NAME}/yukari-agent:latest -t asia.gcr.io/${PROJECT_NAME}/yukari-agent:$CIRCLE_SHA1 .
            docker tag asia.gcr.io/${PROJECT_NAME}/yukari-agent:$CIRCLE_SHA1 asia.gcr.io/${PROJECT_NAME}/yukari-agent:latest
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar asia.gcr.io/${PROJECT_NAME}/yukari-agent:latest
      - save_cache:
          key: v1--
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.test.yml run --rm yukari-agent
